### ISSUE TITLE
Cannot start jquery insert plugin

### ISSUE THREAD

**Issue by imatsu** [orthes/medium-editor-insert-plugin#198]
I installed all the dependencies using bower and the last release of the plugin, and get it this error

```
Uncaught TypeError: Cannot set property 'updatePlaceholder' of undefinedCore   core.js:73
```

**Comment by j0k3r** [comment]
This should be fixed as soon as #196 will be merged.
But before that, you can lock bower deps of medium-editor to 4.11.1. And you'll be able to use the medium-editor-insert-plugin.

**Comment by robodisco** [comment]
Hello,

Hi there, 

I tried locking as you said and actually set the insert plugin version down to 1.7 to resolve dependency issues. My  bower file now looks like this 

{
  "name": "dsl-generated dependencies",
  "dependencies": {
    "medium-editor": "4.11.1",
    "medium-editor-insert-plugin": "1.7.0"
  }
}

yet I still get

```
"Uncaught TypeError: Cannot set property 'updatePlaceholder' of undefined".
```

 Im using a div to create the editor and **not a textarea** like so

```html
<div class="editable" data-editable="true"></div>

<script>
  $(document).ready(function(){
    var editor = new MediumEditor('div[data-editable=true]', {
      placeholder: false
    });

    $('div[data-editable=true]').mediumInsert({
          editor: editor
    });
  });
</script>
```

Could you tell me the exact versions which should work together so i can isolate this bug?

**Comment by j0k3r** [comment]
Did you try to jump to 2.0.1 instead ?

I'm using medium-editor-insert-plugin @ 2.0.1 with medium-editor @ 5.0.0 without any problems. If you made some custom extension for medium-editor, you can easily update them following the [Upgrade file](https://github.com/yabwe/medium-editor/blob/master/UPGRADE-5.md).

After few tests, it seems that you need to lock medium-editor @ 4.10.1. Placeholder has been [converted to an extension on the 4.10.2](https://github.com/yabwe/medium-editor/commit/479e83b49b0fcdf6da96cd205df694c39333e209) (a bit too early I think)

**Comment by robodisco** [comment]
Hi @j0k3r 

Thanks for a very quick reply.

Ok i locked medium editor to 4.10.1 and insert plugin to 2.01.

But i still get the same error 

```sh
Uncaught TypeError: Cannot set property 'updatePlaceholder' of undefined
```
Chrome inspector tells me its failing on the last line of the Core function 

```js
 function Core (el, options) {
        var editor;

        this.el = el;
        this.$el = $(el);
        this.templates = window.MediumInsert.Templates;

        if (options) {
            // Fix #142
            // Avoid deep copying editor object, because since v2.3.0 it contains circular references which causes jQuery.extend to break
            // Instead copy editor object to this.options manually
            editor = options.editor;
            options.editor = null;
        }
        this.options = $.extend(true, {}, defaults, options);
        this.options.editor = editor;

        this._defaults = defaults;
        this._name = pluginName;

        // Extend editor's functions
        if (this.options && this.options.editor) {
            this.options.editor._serialize = this.options.editor.serialize;
            this.options.editor._destroy = this.options.editor.destroy;
            this.options.editor._setup = this.options.editor.setup;
            this.options.editor._hideInsertButtons = this.hideButtons;

            this.options.editor.serialize = this.editorSerialize;
            this.options.editor.destroy = this.editorDestroy;
            this.options.editor.setup = this.editorSetup;

            this.options.editor.getExtensionByName('placeholder').updatePlaceholder = this.editorUpdatePlaceholder;  // <<---- FAILS HERE 
        }
    }
```

Here's how i'm requiring the various dependencies (its a rails project but they are all getting loaded)

```js
//= require jquery
//= require jquery_ujs
//= require bootstrap-sprockets
//= require cocoon
//= require typed
//= require medium-editor/dist/js/medium-editor
//= require handlebars/handlebars.runtime
//= require jquery-sortable/source/js/jquery-sortable
//= require blueimp-file-upload/js/vendor/jquery.ui.widget.js
//= require blueimp-file-upload/js/jquery.iframe-transport.js
//= require blueimp-file-upload/js/jquery.fileupload.js
//= require medium-editor-insert-plugin/dist/js/medium-editor-insert-plugin
//= require_tree .
```

here is my bower file

```json
{
  "name": "dsl-generated dependencies",
  "dependencies": {
    "medium-editor": "4.10.1",
    "medium-editor-insert-plugin": "2.0.1"
  }
}
```

**Comment by robodisco** [comment]
Actually ive created a standalone repo which reproduces this bug. You can see it here if it helps. Load up the index.html page in the browser with chorme inspect and you can see the error in the console.

https://github.com/robodisco/medium-editor-insert-plugin-bug

**Comment by j0k3r** [comment]
You misunderstood what I said :smile: 

If you choose to use medium-editor-insert-plugin 2.0.1 you **must** use medium-editor > 4.10.1. And if you choose this option, I recommend you to use medium-editor 5.2.0.

Your bower.json should be like that:

```json
{
  "dependencies": {
    "medium-editor-insert-plugin": "^2.0",
    "medium-editor": "^5.0.0"
  },
  "resolutions": {
    "medium-editor": "^5.0.0"
  }
}
```

> The `resolutions` is here to force bower to use the latest of medium-editor because medium-editor-insert-plugin lock < 5.0.0

**Comment by robodisco** [comment]
Haha sorry - yes I wasn't 100% sure what you meant in your earlier comment. Thanks for clarification. Good news its working. 

Thank you for you help! :-)
